### ISSUE TITLE
Good example for my binder?

### ISSUE THREAD

**Issue by sje30** [sofroniewn/sofroniew-vlasov-2015#2]
hi Nick,

I see you've been having a great time since leaving Cambridge.  Apologies for sending this via an issue, but I wonder if you have any recommendations about a good example notebook for demonstrating my binder.org?  I'm giving a talk at FENS about reproducible research, and I'd like to demo my binder -- is this repo suitable?  It worked okay, but in the interests of explaining things, perhaps a shorter one might work?  (If not, I can create one, no problem.)

Thanks, Stephen

**Comment by sofroniewn** [comment]
Hi Stephen
Great to hear from you! From this repo I'd recommend showing the imaging_tables notebook, it's the most self contained one notebook. The other repo I've made coupled to a paper is this one https://github.com/sofroniewn/2pRAM-paper.

You might have the most success with the LIGO binder
https://github.com/minrk/ligo-binder made with the notebooks released by the gravitational waves team.

Best
Nick

**Comment by sje30** [comment]
Thanks Nick -- got this one.  This binder service is excellent.

Slides are at: http://sje30.github.io/talks/2016/fens_eglen.html
S

**Comment by sofroniewn** [comment]
Great, you should join the binder [gitter](https://gitter.im/binder-project/binder), if you're not already there as it is the place to go for support

**Comment by sje30** [comment]
> Great, you should join the binder [gitter](https://gitter.im/binder-project/binder), if you're not already there as it is the place to go for support
> sure!
